<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="title">
        <div class="wrp-isnc-news">
        <span><?= $block->escapeHtml(__('sign up for our')) ?></span>
        <strong><?= $block->escapeHtml(__('NEWSLETTER')) ?></strong>
        </div>
    </div>
    <div class="wrp-msg">
        <span><?= $block->escapeHtml(__('to win ')) ?></span>
        <strong><?= $block->escapeHtml(__('10% off ')) ?></strong>
        <span><?= $block->escapeHtml(__('in the first purchase')) ?></span>
    </div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="wrp-news">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                    </label>
                    <div class="wrp-input-news">
                        <input name="email" type="email" id="newsmail"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                        <input name="nome" type="email" id="newsname"
                               placeholder="<?= $block->escapeHtml(__('Enter your name')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Send')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }

</script>
